/* eslint-disable */

// @ts-nocheck

// noinspection JSUnusedGlobalSymbols

// This file was automatically generated by TanStack Router.
// You should NOT make any changes in this file as it will be overwritten.
// Additionally, you should also exclude this file from your linter and/or formatter to prevent it from being checked or modified.

import { Route as rootRouteImport } from './routes/__root'
import { Route as MeRouteImport } from './routes/me'
import { Route as LandingRouteImport } from './routes/landing'
import { Route as GaussSplattingRouteImport } from './routes/gauss-splatting'
import { Route as UserRouteImport } from './routes/_user'
import { Route as TestRouteImport } from './routes/_test'
import { Route as GameRouteImport } from './routes/_game'
import { Route as AuthRouteImport } from './routes/_auth'
import { Route as IndexRouteImport } from './routes/index'
import { Route as UserTopUpTokensRouteImport } from './routes/_user/top-up-tokens'
import { Route as UserTokenUsageRouteImport } from './routes/_user/token-usage'
import { Route as UserSubscriptionPlansRouteImport } from './routes/_user/subscription-plans'
import { Route as UserSettingsRouteImport } from './routes/_user/settings'
import { Route as UserAccountRouteImport } from './routes/_user/account'
import { Route as TestStripeTestRouteImport } from './routes/_test/stripe-test'
import { Route as TestResourcesManagerRouteImport } from './routes/_test/resources-manager'
import { Route as TestMicroWebTestRouteImport } from './routes/_test/micro-web-test'
import { Route as TestLiquidGlassTestRouteImport } from './routes/_test/liquid-glass-test'
import { Route as TestItemsManagerRouteImport } from './routes/_test/items-manager'
import { Route as TestIframeTestRouteImport } from './routes/_test/iframe-test'
import { Route as TestGsSceneTestRouteImport } from './routes/_test/gs-scene-test'
import { Route as TestGameDataTestRouteImport } from './routes/_test/game-data-test'
import { Route as TestChatTestRouteImport } from './routes/_test/chat-test'
import { Route as TestAuthTestRouteImport } from './routes/_test/auth-test'
import { Route as GameTimelineRouteImport } from './routes/_game/timeline'
import { Route as GameQuestRouteImport } from './routes/_game/quest'
import { Route as GameMemoriesRouteImport } from './routes/_game/memories'
import { Route as AuthRegisterRouteImport } from './routes/_auth/register'
import { Route as AuthLoginRouteImport } from './routes/_auth/login'
import { Route as AuthForgotPasswordResetRouteImport } from './routes/_auth/forgot-password-reset'
import { Route as AuthForgotPasswordRouteImport } from './routes/_auth/forgot-password'
import { Route as GameTownTownIdRouteImport } from './routes/_game/town.$townId'
import { Route as GameCharactersWorldIdRouteImport } from './routes/_game/characters.$worldId'
import { Route as GameTrpgReincarnationRouteImport } from './routes/_game/_trpg/reincarnation'
import { Route as GameTrpgExploreRouteImport } from './routes/_game/_trpg/explore'
import { Route as GameTrpgBooksRouteImport } from './routes/_game/_trpg/books'
import { Route as GameTrpgBattleRouteImport } from './routes/_game/_trpg/battle'
import { Route as GameTrpgAdventureRouteImport } from './routes/_game/_trpg/adventure'
import { Route as GameTrpgAbyssRouteImport } from './routes/_game/_trpg/abyss'
import { Route as GameCompanionPhoneRouteImport } from './routes/_game/_companion/phone'
import { Route as GameCompanionMailRouteImport } from './routes/_game/_companion/mail'
import { Route as GameCompanionAppraisalRouteImport } from './routes/_game/_companion/appraisal'

const MeRoute = MeRouteImport.update({
  id: '/me',
  path: '/me',
  getParentRoute: () => rootRouteImport,
} as any)
const LandingRoute = LandingRouteImport.update({
  id: '/landing',
  path: '/landing',
  getParentRoute: () => rootRouteImport,
} as any)
const GaussSplattingRoute = GaussSplattingRouteImport.update({
  id: '/gauss-splatting',
  path: '/gauss-splatting',
  getParentRoute: () => rootRouteImport,
} as any)
const UserRoute = UserRouteImport.update({
  id: '/_user',
  getParentRoute: () => rootRouteImport,
} as any)
const TestRoute = TestRouteImport.update({
  id: '/_test',
  getParentRoute: () => rootRouteImport,
} as any)
const GameRoute = GameRouteImport.update({
  id: '/_game',
  getParentRoute: () => rootRouteImport,
} as any)
const AuthRoute = AuthRouteImport.update({
  id: '/_auth',
  getParentRoute: () => rootRouteImport,
} as any)
const IndexRoute = IndexRouteImport.update({
  id: '/',
  path: '/',
  getParentRoute: () => rootRouteImport,
} as any)
const UserTopUpTokensRoute = UserTopUpTokensRouteImport.update({
  id: '/top-up-tokens',
  path: '/top-up-tokens',
  getParentRoute: () => UserRoute,
} as any)
const UserTokenUsageRoute = UserTokenUsageRouteImport.update({
  id: '/token-usage',
  path: '/token-usage',
  getParentRoute: () => UserRoute,
} as any)
const UserSubscriptionPlansRoute = UserSubscriptionPlansRouteImport.update({
  id: '/subscription-plans',
  path: '/subscription-plans',
  getParentRoute: () => UserRoute,
} as any)
const UserSettingsRoute = UserSettingsRouteImport.update({
  id: '/settings',
  path: '/settings',
  getParentRoute: () => UserRoute,
} as any)
const UserAccountRoute = UserAccountRouteImport.update({
  id: '/account',
  path: '/account',
  getParentRoute: () => UserRoute,
} as any)
const TestStripeTestRoute = TestStripeTestRouteImport.update({
  id: '/stripe-test',
  path: '/stripe-test',
  getParentRoute: () => TestRoute,
} as any)
const TestResourcesManagerRoute = TestResourcesManagerRouteImport.update({
  id: '/resources-manager',
  path: '/resources-manager',
  getParentRoute: () => TestRoute,
} as any)
const TestMicroWebTestRoute = TestMicroWebTestRouteImport.update({
  id: '/micro-web-test',
  path: '/micro-web-test',
  getParentRoute: () => TestRoute,
} as any)
const TestLiquidGlassTestRoute = TestLiquidGlassTestRouteImport.update({
  id: '/liquid-glass-test',
  path: '/liquid-glass-test',
  getParentRoute: () => TestRoute,
} as any)
const TestItemsManagerRoute = TestItemsManagerRouteImport.update({
  id: '/items-manager',
  path: '/items-manager',
  getParentRoute: () => TestRoute,
} as any)
const TestIframeTestRoute = TestIframeTestRouteImport.update({
  id: '/iframe-test',
  path: '/iframe-test',
  getParentRoute: () => TestRoute,
} as any)
const TestGsSceneTestRoute = TestGsSceneTestRouteImport.update({
  id: '/gs-scene-test',
  path: '/gs-scene-test',
  getParentRoute: () => TestRoute,
} as any)
const TestGameDataTestRoute = TestGameDataTestRouteImport.update({
  id: '/game-data-test',
  path: '/game-data-test',
  getParentRoute: () => TestRoute,
} as any)
const TestChatTestRoute = TestChatTestRouteImport.update({
  id: '/chat-test',
  path: '/chat-test',
  getParentRoute: () => TestRoute,
} as any)
const TestAuthTestRoute = TestAuthTestRouteImport.update({
  id: '/auth-test',
  path: '/auth-test',
  getParentRoute: () => TestRoute,
} as any)
const GameTimelineRoute = GameTimelineRouteImport.update({
  id: '/timeline',
  path: '/timeline',
  getParentRoute: () => GameRoute,
} as any)
const GameQuestRoute = GameQuestRouteImport.update({
  id: '/quest',
  path: '/quest',
  getParentRoute: () => GameRoute,
} as any)
const GameMemoriesRoute = GameMemoriesRouteImport.update({
  id: '/memories',
  path: '/memories',
  getParentRoute: () => GameRoute,
} as any)
const AuthRegisterRoute = AuthRegisterRouteImport.update({
  id: '/register',
  path: '/register',
  getParentRoute: () => AuthRoute,
} as any)
const AuthLoginRoute = AuthLoginRouteImport.update({
  id: '/login',
  path: '/login',
  getParentRoute: () => AuthRoute,
} as any)
const AuthForgotPasswordResetRoute = AuthForgotPasswordResetRouteImport.update({
  id: '/forgot-password-reset',
  path: '/forgot-password-reset',
  getParentRoute: () => AuthRoute,
} as any)
const AuthForgotPasswordRoute = AuthForgotPasswordRouteImport.update({
  id: '/forgot-password',
  path: '/forgot-password',
  getParentRoute: () => AuthRoute,
} as any)
const GameTownTownIdRoute = GameTownTownIdRouteImport.update({
  id: '/town/$townId',
  path: '/town/$townId',
  getParentRoute: () => GameRoute,
} as any)
const GameCharactersWorldIdRoute = GameCharactersWorldIdRouteImport.update({
  id: '/characters/$worldId',
  path: '/characters/$worldId',
  getParentRoute: () => GameRoute,
} as any)
const GameTrpgReincarnationRoute = GameTrpgReincarnationRouteImport.update({
  id: '/_trpg/reincarnation',
  path: '/reincarnation',
  getParentRoute: () => GameRoute,
} as any)
const GameTrpgExploreRoute = GameTrpgExploreRouteImport.update({
  id: '/_trpg/explore',
  path: '/explore',
  getParentRoute: () => GameRoute,
} as any)
const GameTrpgBooksRoute = GameTrpgBooksRouteImport.update({
  id: '/_trpg/books',
  path: '/books',
  getParentRoute: () => GameRoute,
} as any)
const GameTrpgBattleRoute = GameTrpgBattleRouteImport.update({
  id: '/_trpg/battle',
  path: '/battle',
  getParentRoute: () => GameRoute,
} as any)
const GameTrpgAdventureRoute = GameTrpgAdventureRouteImport.update({
  id: '/_trpg/adventure',
  path: '/adventure',
  getParentRoute: () => GameRoute,
} as any)
const GameTrpgAbyssRoute = GameTrpgAbyssRouteImport.update({
  id: '/_trpg/abyss',
  path: '/abyss',
  getParentRoute: () => GameRoute,
} as any)
const GameCompanionPhoneRoute = GameCompanionPhoneRouteImport.update({
  id: '/_companion/phone',
  path: '/phone',
  getParentRoute: () => GameRoute,
} as any)
const GameCompanionMailRoute = GameCompanionMailRouteImport.update({
  id: '/_companion/mail',
  path: '/mail',
  getParentRoute: () => GameRoute,
} as any)
const GameCompanionAppraisalRoute = GameCompanionAppraisalRouteImport.update({
  id: '/_companion/appraisal',
  path: '/appraisal',
  getParentRoute: () => GameRoute,
} as any)

export interface FileRoutesByFullPath {
  '/': typeof IndexRoute
  '/gauss-splatting': typeof GaussSplattingRoute
  '/landing': typeof LandingRoute
  '/me': typeof MeRoute
  '/forgot-password': typeof AuthForgotPasswordRoute
  '/forgot-password-reset': typeof AuthForgotPasswordResetRoute
  '/login': typeof AuthLoginRoute
  '/register': typeof AuthRegisterRoute
  '/memories': typeof GameMemoriesRoute
  '/quest': typeof GameQuestRoute
  '/timeline': typeof GameTimelineRoute
  '/auth-test': typeof TestAuthTestRoute
  '/chat-test': typeof TestChatTestRoute
  '/game-data-test': typeof TestGameDataTestRoute
  '/gs-scene-test': typeof TestGsSceneTestRoute
  '/iframe-test': typeof TestIframeTestRoute
  '/items-manager': typeof TestItemsManagerRoute
  '/liquid-glass-test': typeof TestLiquidGlassTestRoute
  '/micro-web-test': typeof TestMicroWebTestRoute
  '/resources-manager': typeof TestResourcesManagerRoute
  '/stripe-test': typeof TestStripeTestRoute
  '/account': typeof UserAccountRoute
  '/settings': typeof UserSettingsRoute
  '/subscription-plans': typeof UserSubscriptionPlansRoute
  '/token-usage': typeof UserTokenUsageRoute
  '/top-up-tokens': typeof UserTopUpTokensRoute
  '/appraisal': typeof GameCompanionAppraisalRoute
  '/mail': typeof GameCompanionMailRoute
  '/phone': typeof GameCompanionPhoneRoute
  '/abyss': typeof GameTrpgAbyssRoute
  '/adventure': typeof GameTrpgAdventureRoute
  '/battle': typeof GameTrpgBattleRoute
  '/books': typeof GameTrpgBooksRoute
  '/explore': typeof GameTrpgExploreRoute
  '/reincarnation': typeof GameTrpgReincarnationRoute
  '/characters/$worldId': typeof GameCharactersWorldIdRoute
  '/town/$townId': typeof GameTownTownIdRoute
}
export interface FileRoutesByTo {
  '/': typeof IndexRoute
  '/gauss-splatting': typeof GaussSplattingRoute
  '/landing': typeof LandingRoute
  '/me': typeof MeRoute
  '/forgot-password': typeof AuthForgotPasswordRoute
  '/forgot-password-reset': typeof AuthForgotPasswordResetRoute
  '/login': typeof AuthLoginRoute
  '/register': typeof AuthRegisterRoute
  '/memories': typeof GameMemoriesRoute
  '/quest': typeof GameQuestRoute
  '/timeline': typeof GameTimelineRoute
  '/auth-test': typeof TestAuthTestRoute
  '/chat-test': typeof TestChatTestRoute
  '/game-data-test': typeof TestGameDataTestRoute
  '/gs-scene-test': typeof TestGsSceneTestRoute
  '/iframe-test': typeof TestIframeTestRoute
  '/items-manager': typeof TestItemsManagerRoute
  '/liquid-glass-test': typeof TestLiquidGlassTestRoute
  '/micro-web-test': typeof TestMicroWebTestRoute
  '/resources-manager': typeof TestResourcesManagerRoute
  '/stripe-test': typeof TestStripeTestRoute
  '/account': typeof UserAccountRoute
  '/settings': typeof UserSettingsRoute
  '/subscription-plans': typeof UserSubscriptionPlansRoute
  '/token-usage': typeof UserTokenUsageRoute
  '/top-up-tokens': typeof UserTopUpTokensRoute
  '/appraisal': typeof GameCompanionAppraisalRoute
  '/mail': typeof GameCompanionMailRoute
  '/phone': typeof GameCompanionPhoneRoute
  '/abyss': typeof GameTrpgAbyssRoute
  '/adventure': typeof GameTrpgAdventureRoute
  '/battle': typeof GameTrpgBattleRoute
  '/books': typeof GameTrpgBooksRoute
  '/explore': typeof GameTrpgExploreRoute
  '/reincarnation': typeof GameTrpgReincarnationRoute
  '/characters/$worldId': typeof GameCharactersWorldIdRoute
  '/town/$townId': typeof GameTownTownIdRoute
}
export interface FileRoutesById {
  __root__: typeof rootRouteImport
  '/': typeof IndexRoute
  '/_auth': typeof AuthRouteWithChildren
  '/_game': typeof GameRouteWithChildren
  '/_test': typeof TestRouteWithChildren
  '/_user': typeof UserRouteWithChildren
  '/gauss-splatting': typeof GaussSplattingRoute
  '/landing': typeof LandingRoute
  '/me': typeof MeRoute
  '/_auth/forgot-password': typeof AuthForgotPasswordRoute
  '/_auth/forgot-password-reset': typeof AuthForgotPasswordResetRoute
  '/_auth/login': typeof AuthLoginRoute
  '/_auth/register': typeof AuthRegisterRoute
  '/_game/memories': typeof GameMemoriesRoute
  '/_game/quest': typeof GameQuestRoute
  '/_game/timeline': typeof GameTimelineRoute
  '/_test/auth-test': typeof TestAuthTestRoute
  '/_test/chat-test': typeof TestChatTestRoute
  '/_test/game-data-test': typeof TestGameDataTestRoute
  '/_test/gs-scene-test': typeof TestGsSceneTestRoute
  '/_test/iframe-test': typeof TestIframeTestRoute
  '/_test/items-manager': typeof TestItemsManagerRoute
  '/_test/liquid-glass-test': typeof TestLiquidGlassTestRoute
  '/_test/micro-web-test': typeof TestMicroWebTestRoute
  '/_test/resources-manager': typeof TestResourcesManagerRoute
  '/_test/stripe-test': typeof TestStripeTestRoute
  '/_user/account': typeof UserAccountRoute
  '/_user/settings': typeof UserSettingsRoute
  '/_user/subscription-plans': typeof UserSubscriptionPlansRoute
  '/_user/token-usage': typeof UserTokenUsageRoute
  '/_user/top-up-tokens': typeof UserTopUpTokensRoute
  '/_game/_companion/appraisal': typeof GameCompanionAppraisalRoute
  '/_game/_companion/mail': typeof GameCompanionMailRoute
  '/_game/_companion/phone': typeof GameCompanionPhoneRoute
  '/_game/_trpg/abyss': typeof GameTrpgAbyssRoute
  '/_game/_trpg/adventure': typeof GameTrpgAdventureRoute
  '/_game/_trpg/battle': typeof GameTrpgBattleRoute
  '/_game/_trpg/books': typeof GameTrpgBooksRoute
  '/_game/_trpg/explore': typeof GameTrpgExploreRoute
  '/_game/_trpg/reincarnation': typeof GameTrpgReincarnationRoute
  '/_game/characters/$worldId': typeof GameCharactersWorldIdRoute
  '/_game/town/$townId': typeof GameTownTownIdRoute
}
export interface FileRouteTypes {
  fileRoutesByFullPath: FileRoutesByFullPath
  fullPaths:
    | '/'
    | '/gauss-splatting'
    | '/landing'
    | '/me'
    | '/forgot-password'
    | '/forgot-password-reset'
    | '/login'
    | '/register'
    | '/memories'
    | '/quest'
    | '/timeline'
    | '/auth-test'
    | '/chat-test'
    | '/game-data-test'
    | '/gs-scene-test'
    | '/iframe-test'
    | '/items-manager'
    | '/liquid-glass-test'
    | '/micro-web-test'
    | '/resources-manager'
    | '/stripe-test'
    | '/account'
    | '/settings'
    | '/subscription-plans'
    | '/token-usage'
    | '/top-up-tokens'
    | '/appraisal'
    | '/mail'
    | '/phone'
    | '/abyss'
    | '/adventure'
    | '/battle'
    | '/books'
    | '/explore'
    | '/reincarnation'
    | '/characters/$worldId'
    | '/town/$townId'
  fileRoutesByTo: FileRoutesByTo
  to:
    | '/'
    | '/gauss-splatting'
    | '/landing'
    | '/me'
    | '/forgot-password'
    | '/forgot-password-reset'
    | '/login'
    | '/register'
    | '/memories'
    | '/quest'
    | '/timeline'
    | '/auth-test'
    | '/chat-test'
    | '/game-data-test'
    | '/gs-scene-test'
    | '/iframe-test'
    | '/items-manager'
    | '/liquid-glass-test'
    | '/micro-web-test'
    | '/resources-manager'
    | '/stripe-test'
    | '/account'
    | '/settings'
    | '/subscription-plans'
    | '/token-usage'
    | '/top-up-tokens'
    | '/appraisal'
    | '/mail'
    | '/phone'
    | '/abyss'
    | '/adventure'
    | '/battle'
    | '/books'
    | '/explore'
    | '/reincarnation'
    | '/characters/$worldId'
    | '/town/$townId'
  id:
    | '__root__'
    | '/'
    | '/_auth'
    | '/_game'
    | '/_test'
    | '/_user'
    | '/gauss-splatting'
    | '/landing'
    | '/me'
    | '/_auth/forgot-password'
    | '/_auth/forgot-password-reset'
    | '/_auth/login'
    | '/_auth/register'
    | '/_game/memories'
    | '/_game/quest'
    | '/_game/timeline'
    | '/_test/auth-test'
    | '/_test/chat-test'
    | '/_test/game-data-test'
    | '/_test/gs-scene-test'
    | '/_test/iframe-test'
    | '/_test/items-manager'
    | '/_test/liquid-glass-test'
    | '/_test/micro-web-test'
    | '/_test/resources-manager'
    | '/_test/stripe-test'
    | '/_user/account'
    | '/_user/settings'
    | '/_user/subscription-plans'
    | '/_user/token-usage'
    | '/_user/top-up-tokens'
    | '/_game/_companion/appraisal'
    | '/_game/_companion/mail'
    | '/_game/_companion/phone'
    | '/_game/_trpg/abyss'
    | '/_game/_trpg/adventure'
    | '/_game/_trpg/battle'
    | '/_game/_trpg/books'
    | '/_game/_trpg/explore'
    | '/_game/_trpg/reincarnation'
    | '/_game/characters/$worldId'
    | '/_game/town/$townId'
  fileRoutesById: FileRoutesById
}
export interface RootRouteChildren {
  IndexRoute: typeof IndexRoute
  AuthRoute: typeof AuthRouteWithChildren
  GameRoute: typeof GameRouteWithChildren
  TestRoute: typeof TestRouteWithChildren
  UserRoute: typeof UserRouteWithChildren
  GaussSplattingRoute: typeof GaussSplattingRoute
  LandingRoute: typeof LandingRoute
  MeRoute: typeof MeRoute
}

declare module '@tanstack/react-router' {
  interface FileRoutesByPath {
    '/me': {
      id: '/me'
      path: '/me'
      fullPath: '/me'
      preLoaderRoute: typeof MeRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/landing': {
      id: '/landing'
      path: '/landing'
      fullPath: '/landing'
      preLoaderRoute: typeof LandingRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/gauss-splatting': {
      id: '/gauss-splatting'
      path: '/gauss-splatting'
      fullPath: '/gauss-splatting'
      preLoaderRoute: typeof GaussSplattingRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/_user': {
      id: '/_user'
      path: ''
      fullPath: '/'
      preLoaderRoute: typeof UserRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/_test': {
      id: '/_test'
      path: ''
      fullPath: '/'
      preLoaderRoute: typeof TestRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/_game': {
      id: '/_game'
      path: ''
      fullPath: '/'
      preLoaderRoute: typeof GameRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/_auth': {
      id: '/_auth'
      path: ''
      fullPath: '/'
      preLoaderRoute: typeof AuthRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/': {
      id: '/'
      path: '/'
      fullPath: '/'
      preLoaderRoute: typeof IndexRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/_user/top-up-tokens': {
      id: '/_user/top-up-tokens'
      path: '/top-up-tokens'
      fullPath: '/top-up-tokens'
      preLoaderRoute: typeof UserTopUpTokensRouteImport
      parentRoute: typeof UserRoute
    }
    '/_user/token-usage': {
      id: '/_user/token-usage'
      path: '/token-usage'
      fullPath: '/token-usage'
      preLoaderRoute: typeof UserTokenUsageRouteImport
      parentRoute: typeof UserRoute
    }
    '/_user/subscription-plans': {
      id: '/_user/subscription-plans'
      path: '/subscription-plans'
      fullPath: '/subscription-plans'
      preLoaderRoute: typeof UserSubscriptionPlansRouteImport
      parentRoute: typeof UserRoute
    }
    '/_user/settings': {
      id: '/_user/settings'
      path: '/settings'
      fullPath: '/settings'
      preLoaderRoute: typeof UserSettingsRouteImport
      parentRoute: typeof UserRoute
    }
    '/_user/account': {
      id: '/_user/account'
      path: '/account'
      fullPath: '/account'
      preLoaderRoute: typeof UserAccountRouteImport
      parentRoute: typeof UserRoute
    }
    '/_test/stripe-test': {
      id: '/_test/stripe-test'
      path: '/stripe-test'
      fullPath: '/stripe-test'
      preLoaderRoute: typeof TestStripeTestRouteImport
      parentRoute: typeof TestRoute
    }
    '/_test/resources-manager': {
      id: '/_test/resources-manager'
      path: '/resources-manager'
      fullPath: '/resources-manager'
      preLoaderRoute: typeof TestResourcesManagerRouteImport
      parentRoute: typeof TestRoute
    }
    '/_test/micro-web-test': {
      id: '/_test/micro-web-test'
      path: '/micro-web-test'
      fullPath: '/micro-web-test'
      preLoaderRoute: typeof TestMicroWebTestRouteImport
      parentRoute: typeof TestRoute
    }
    '/_test/liquid-glass-test': {
      id: '/_test/liquid-glass-test'
      path: '/liquid-glass-test'
      fullPath: '/liquid-glass-test'
      preLoaderRoute: typeof TestLiquidGlassTestRouteImport
      parentRoute: typeof TestRoute
    }
    '/_test/items-manager': {
      id: '/_test/items-manager'
      path: '/items-manager'
      fullPath: '/items-manager'
      preLoaderRoute: typeof TestItemsManagerRouteImport
      parentRoute: typeof TestRoute
    }
    '/_test/iframe-test': {
      id: '/_test/iframe-test'
      path: '/iframe-test'
      fullPath: '/iframe-test'
      preLoaderRoute: typeof TestIframeTestRouteImport
      parentRoute: typeof TestRoute
    }
    '/_test/gs-scene-test': {
      id: '/_test/gs-scene-test'
      path: '/gs-scene-test'
      fullPath: '/gs-scene-test'
      preLoaderRoute: typeof TestGsSceneTestRouteImport
      parentRoute: typeof TestRoute
    }
    '/_test/game-data-test': {
      id: '/_test/game-data-test'
      path: '/game-data-test'
      fullPath: '/game-data-test'
      preLoaderRoute: typeof TestGameDataTestRouteImport
      parentRoute: typeof TestRoute
    }
    '/_test/chat-test': {
      id: '/_test/chat-test'
      path: '/chat-test'
      fullPath: '/chat-test'
      preLoaderRoute: typeof TestChatTestRouteImport
      parentRoute: typeof TestRoute
    }
    '/_test/auth-test': {
      id: '/_test/auth-test'
      path: '/auth-test'
      fullPath: '/auth-test'
      preLoaderRoute: typeof TestAuthTestRouteImport
      parentRoute: typeof TestRoute
    }
    '/_game/timeline': {
      id: '/_game/timeline'
      path: '/timeline'
      fullPath: '/timeline'
      preLoaderRoute: typeof GameTimelineRouteImport
      parentRoute: typeof GameRoute
    }
    '/_game/quest': {
      id: '/_game/quest'
      path: '/quest'
      fullPath: '/quest'
      preLoaderRoute: typeof GameQuestRouteImport
      parentRoute: typeof GameRoute
    }
    '/_game/memories': {
      id: '/_game/memories'
      path: '/memories'
      fullPath: '/memories'
      preLoaderRoute: typeof GameMemoriesRouteImport
      parentRoute: typeof GameRoute
    }
    '/_auth/register': {
      id: '/_auth/register'
      path: '/register'
      fullPath: '/register'
      preLoaderRoute: typeof AuthRegisterRouteImport
      parentRoute: typeof AuthRoute
    }
    '/_auth/login': {
      id: '/_auth/login'
      path: '/login'
      fullPath: '/login'
      preLoaderRoute: typeof AuthLoginRouteImport
      parentRoute: typeof AuthRoute
    }
    '/_auth/forgot-password-reset': {
      id: '/_auth/forgot-password-reset'
      path: '/forgot-password-reset'
      fullPath: '/forgot-password-reset'
      preLoaderRoute: typeof AuthForgotPasswordResetRouteImport
      parentRoute: typeof AuthRoute
    }
    '/_auth/forgot-password': {
      id: '/_auth/forgot-password'
      path: '/forgot-password'
      fullPath: '/forgot-password'
      preLoaderRoute: typeof AuthForgotPasswordRouteImport
      parentRoute: typeof AuthRoute
    }
    '/_game/town/$townId': {
      id: '/_game/town/$townId'
      path: '/town/$townId'
      fullPath: '/town/$townId'
      preLoaderRoute: typeof GameTownTownIdRouteImport
      parentRoute: typeof GameRoute
    }
    '/_game/characters/$worldId': {
      id: '/_game/characters/$worldId'
      path: '/characters/$worldId'
      fullPath: '/characters/$worldId'
      preLoaderRoute: typeof GameCharactersWorldIdRouteImport
      parentRoute: typeof GameRoute
    }
    '/_game/_trpg/reincarnation': {
      id: '/_game/_trpg/reincarnation'
      path: '/reincarnation'
      fullPath: '/reincarnation'
      preLoaderRoute: typeof GameTrpgReincarnationRouteImport
      parentRoute: typeof GameRoute
    }
    '/_game/_trpg/explore': {
      id: '/_game/_trpg/explore'
      path: '/explore'
      fullPath: '/explore'
      preLoaderRoute: typeof GameTrpgExploreRouteImport
      parentRoute: typeof GameRoute
    }
    '/_game/_trpg/books': {
      id: '/_game/_trpg/books'
      path: '/books'
      fullPath: '/books'
      preLoaderRoute: typeof GameTrpgBooksRouteImport
      parentRoute: typeof GameRoute
    }
    '/_game/_trpg/battle': {
      id: '/_game/_trpg/battle'
      path: '/battle'
      fullPath: '/battle'
      preLoaderRoute: typeof GameTrpgBattleRouteImport
      parentRoute: typeof GameRoute
    }
    '/_game/_trpg/adventure': {
      id: '/_game/_trpg/adventure'
      path: '/adventure'
      fullPath: '/adventure'
      preLoaderRoute: typeof GameTrpgAdventureRouteImport
      parentRoute: typeof GameRoute
    }
    '/_game/_trpg/abyss': {
      id: '/_game/_trpg/abyss'
      path: '/abyss'
      fullPath: '/abyss'
      preLoaderRoute: typeof GameTrpgAbyssRouteImport
      parentRoute: typeof GameRoute
    }
    '/_game/_companion/phone': {
      id: '/_game/_companion/phone'
      path: '/phone'
      fullPath: '/phone'
      preLoaderRoute: typeof GameCompanionPhoneRouteImport
      parentRoute: typeof GameRoute
    }
    '/_game/_companion/mail': {
      id: '/_game/_companion/mail'
      path: '/mail'
      fullPath: '/mail'
      preLoaderRoute: typeof GameCompanionMailRouteImport
      parentRoute: typeof GameRoute
    }
    '/_game/_companion/appraisal': {
      id: '/_game/_companion/appraisal'
      path: '/appraisal'
      fullPath: '/appraisal'
      preLoaderRoute: typeof GameCompanionAppraisalRouteImport
      parentRoute: typeof GameRoute
    }
  }
}

interface AuthRouteChildren {
  AuthForgotPasswordRoute: typeof AuthForgotPasswordRoute
  AuthForgotPasswordResetRoute: typeof AuthForgotPasswordResetRoute
  AuthLoginRoute: typeof AuthLoginRoute
  AuthRegisterRoute: typeof AuthRegisterRoute
}

const AuthRouteChildren: AuthRouteChildren = {
  AuthForgotPasswordRoute: AuthForgotPasswordRoute,
  AuthForgotPasswordResetRoute: AuthForgotPasswordResetRoute,
  AuthLoginRoute: AuthLoginRoute,
  AuthRegisterRoute: AuthRegisterRoute,
}

const AuthRouteWithChildren = AuthRoute._addFileChildren(AuthRouteChildren)

interface GameRouteChildren {
  GameMemoriesRoute: typeof GameMemoriesRoute
  GameQuestRoute: typeof GameQuestRoute
  GameTimelineRoute: typeof GameTimelineRoute
  GameCompanionAppraisalRoute: typeof GameCompanionAppraisalRoute
  GameCompanionMailRoute: typeof GameCompanionMailRoute
  GameCompanionPhoneRoute: typeof GameCompanionPhoneRoute
  GameTrpgAbyssRoute: typeof GameTrpgAbyssRoute
  GameTrpgAdventureRoute: typeof GameTrpgAdventureRoute
  GameTrpgBattleRoute: typeof GameTrpgBattleRoute
  GameTrpgBooksRoute: typeof GameTrpgBooksRoute
  GameTrpgExploreRoute: typeof GameTrpgExploreRoute
  GameTrpgReincarnationRoute: typeof GameTrpgReincarnationRoute
  GameCharactersWorldIdRoute: typeof GameCharactersWorldIdRoute
  GameTownTownIdRoute: typeof GameTownTownIdRoute
}

const GameRouteChildren: GameRouteChildren = {
  GameMemoriesRoute: GameMemoriesRoute,
  GameQuestRoute: GameQuestRoute,
  GameTimelineRoute: GameTimelineRoute,
  GameCompanionAppraisalRoute: GameCompanionAppraisalRoute,
  GameCompanionMailRoute: GameCompanionMailRoute,
  GameCompanionPhoneRoute: GameCompanionPhoneRoute,
  GameTrpgAbyssRoute: GameTrpgAbyssRoute,
  GameTrpgAdventureRoute: GameTrpgAdventureRoute,
  GameTrpgBattleRoute: GameTrpgBattleRoute,
  GameTrpgBooksRoute: GameTrpgBooksRoute,
  GameTrpgExploreRoute: GameTrpgExploreRoute,
  GameTrpgReincarnationRoute: GameTrpgReincarnationRoute,
  GameCharactersWorldIdRoute: GameCharactersWorldIdRoute,
  GameTownTownIdRoute: GameTownTownIdRoute,
}

const GameRouteWithChildren = GameRoute._addFileChildren(GameRouteChildren)

interface TestRouteChildren {
  TestAuthTestRoute: typeof TestAuthTestRoute
  TestChatTestRoute: typeof TestChatTestRoute
  TestGameDataTestRoute: typeof TestGameDataTestRoute
  TestGsSceneTestRoute: typeof TestGsSceneTestRoute
  TestIframeTestRoute: typeof TestIframeTestRoute
  TestItemsManagerRoute: typeof TestItemsManagerRoute
  TestLiquidGlassTestRoute: typeof TestLiquidGlassTestRoute
  TestMicroWebTestRoute: typeof TestMicroWebTestRoute
  TestResourcesManagerRoute: typeof TestResourcesManagerRoute
  TestStripeTestRoute: typeof TestStripeTestRoute
}

const TestRouteChildren: TestRouteChildren = {
  TestAuthTestRoute: TestAuthTestRoute,
  TestChatTestRoute: TestChatTestRoute,
  TestGameDataTestRoute: TestGameDataTestRoute,
  TestGsSceneTestRoute: TestGsSceneTestRoute,
  TestIframeTestRoute: TestIframeTestRoute,
  TestItemsManagerRoute: TestItemsManagerRoute,
  TestLiquidGlassTestRoute: TestLiquidGlassTestRoute,
  TestMicroWebTestRoute: TestMicroWebTestRoute,
  TestResourcesManagerRoute: TestResourcesManagerRoute,
  TestStripeTestRoute: TestStripeTestRoute,
}

const TestRouteWithChildren = TestRoute._addFileChildren(TestRouteChildren)

interface UserRouteChildren {
  UserAccountRoute: typeof UserAccountRoute
  UserSettingsRoute: typeof UserSettingsRoute
  UserSubscriptionPlansRoute: typeof UserSubscriptionPlansRoute
  UserTokenUsageRoute: typeof UserTokenUsageRoute
  UserTopUpTokensRoute: typeof UserTopUpTokensRoute
}

const UserRouteChildren: UserRouteChildren = {
  UserAccountRoute: UserAccountRoute,
  UserSettingsRoute: UserSettingsRoute,
  UserSubscriptionPlansRoute: UserSubscriptionPlansRoute,
  UserTokenUsageRoute: UserTokenUsageRoute,
  UserTopUpTokensRoute: UserTopUpTokensRoute,
}

const UserRouteWithChildren = UserRoute._addFileChildren(UserRouteChildren)

const rootRouteChildren: RootRouteChildren = {
  IndexRoute: IndexRoute,
  AuthRoute: AuthRouteWithChildren,
  GameRoute: GameRouteWithChildren,
  TestRoute: TestRouteWithChildren,
  UserRoute: UserRouteWithChildren,
  GaussSplattingRoute: GaussSplattingRoute,
  LandingRoute: LandingRoute,
  MeRoute: MeRoute,
}
export const routeTree = rootRouteImport
  ._addFileChildren(rootRouteChildren)
  ._addFileTypes<FileRouteTypes>()
